spring:
  application:
    name: pring-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 2224


eureka:
  instance:
    hostname: localhost
  client:
    service-url.defaultZone: http://localhost:7000/eureka/
